"""add alerts table

Revision ID: 4a43c7763433
Revises: c767560ecd4f
Create Date: 2026-09-03 09:39:32.971892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a43c7763433'
down_revision: Union[str, None] = 'c767560ecd4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=32), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('direction', sa.Enum('ABOVE', 'BELOW', name='alert_direction_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIGGERED', 'CANCELLED', name='alert_status_enum'), nullable=False),
    sa.Column('price_at_creation', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
